export { compileCorpus, analyzeCorpus, compileAnalysis, COMPILER_VERSION } from "./lib/pipeline.js";
export { loadCorpus } from "./lib/loadCorpus.js";
export { spellingLexiconPlugin } from "./lib/vocabulary.js";
export { dictionaryEntriesFromEquivalences } from "./lib/compile.js";
export { loadDecisions, validateDecisions, DecisionError } from "./lib/decisions.js";
export { equivalenceId, synonymId } from "./lib/ids.js";
export { LIFECYCLE } from "./lib/lifecycle.js";
export { hashJson } from "./lib/hash.js";
export { annotateReviewQueue, sortPending, decisionSkeleton } from "./lib/queue.js";
export { isInflectionPair } from "./lib/synonyms.js";
export { isMaterialChange } from "./lib/delta.js";
